{
 "title": "Nautobot Application Metrics",
 "description": "Nautobot Application Dashboard",
 "tags": [
  "nautobot",
  "app_metrics"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nautobot_app_metrics_processing_ms, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(django_db_new_connections_total{namespace=~\"$namespace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sites",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nautobot_model_count{name=\"Site\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nautobot_model_count{name=\"Device\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Racks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nautobot_model_count{name=\"Rack\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Prefixes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nautobot_model_count{name=\"Prefix\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "IP Addresses",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nautobot_model_count{name=\"IPAddress\",namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Processing Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nautobot_app_metrics_processing_ms{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Nautobot Workers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nautobot_queue_number_workers{name=\"default\"})"
    }
   ]
  },
  {
   "title": "RQ Failed Tasks by Queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(nautobot_queue_number_jobs{status=~\"failed\", namespace=~\"$namespace\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Job Results",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (status) (nautobot_queue_number_jobs{namespace=~\"$namespace\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Job Results",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nautobot_queue_number_jobs{name=\"default\",namespace=~\"$namespace\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Worker DB Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "instance" },
  {
   "title": "$instance Cache Hits",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}/(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}+cacheops_cache_miss_total{namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Cache Hits"
    }
   ]
  },
  {
   "title": "$instance Database Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "sum by (le) (django_db_query_duration_seconds_bucket{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Worker DB Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "$instance Cache Hits",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}/(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}+cacheops_cache_miss_total{namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Cache Hits"
    }
   ]
  },
  {
   "title": "$instance Database Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 34 },
   "targets": [
    {
     "expr": "sum by (le) (django_db_query_duration_seconds_bucket{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Worker DB Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "$instance Cache Hits",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}/(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}+cacheops_cache_miss_total{namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Cache Hits"
    }
   ]
  },
  {
   "title": "$instance Database Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 46 },
   "targets": [
    {
     "expr": "sum by (le) (django_db_query_duration_seconds_bucket{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Worker DB Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "$instance Cache Hits",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}/(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}+cacheops_cache_miss_total{namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Cache Hits"
    }
   ]
  },
  {
   "title": "$instance Database Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 58 },
   "targets": [
    {
     "expr": "sum by (le) (django_db_query_duration_seconds_bucket{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Worker DB Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "$instance Cache Hits",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}/(cacheops_cache_hit_total{namespace=~\"$namespace\", instance=~\"$instance\"}+cacheops_cache_miss_total{namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Cache Hits"
    }
   ]
  },
  {
   "title": "$instance Database Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 21, "x": 3, "y": 70 },
   "targets": [
    {
     "expr": "sum by (le) (django_db_query_duration_seconds_bucket{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}