{
 "title": "Nautobot Internals",
 "tags": [ "nautobot" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(django_db_new_connections_total, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(django_db_new_connections_total{namespace=~\"$namespace\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(django_db_new_connections_total{job=~\"$job\",namespace=~\"$namespace\"}, instance)"
    }
   },
   {
    "name": "view",
    "label": "View",
    "query": {
     "query": "label_values(django_http_requests_latency_seconds_by_view_method_bucket{job=~\"$job\",namespace=~\"$namespace\", instance=~\"$instance\"}, view)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nautobot Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"$job\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_method_total{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))*60",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "P95 Average Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(.95, django_http_requests_latency_including_middlewares_seconds_bucket{job=\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "P95 Average DB Query Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(.95, django_db_query_duration_seconds_bucket{job=\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Query Time"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cacheops_cache_hit_total{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}/(cacheops_cache_hit_total{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}+cacheops_cache_miss_total{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}))",
     "legendFormat": "Cache Hits"
    }
   ]
  },
  {
   "title": "Success (2xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"2..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Success 2xx"
    }
   ]
  },
  {
   "title": "Redirects (3xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"3..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Redirects 3xx"
    }
   ]
  },
  {
   "title": "Server Errors (5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"5..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "5xx Errors"
    }
   ]
  },
  {
   "title": "Error (4xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"4..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Errors 4xx"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top 10 Views",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by (view) (increase(django_http_requests_latency_seconds_by_view_method_count{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "{{view}}"
    }
   ]
  },
  {
   "title": "Request Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(django_http_requests_latency_including_middlewares_seconds_sum{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))/sum(rate(django_http_requests_latency_including_middlewares_seconds_count{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Request Latency by View",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (view) (irate(django_http_requests_latency_seconds_by_view_method_sum{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))/sum by (view) (irate(django_http_requests_latency_seconds_by_view_method_count{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{ view }}"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"5..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Server Error"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"2..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"3..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Redirect"
    },
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{job=~\"$job\", status=~\"4..\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Client Error"
    }
   ]
  },
  {
   "title": "Request Size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (django_http_requests_body_total_bytes_bucket{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Database Query Duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (le) (django_db_query_duration_seconds_bucket{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Database Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(irate(django_db_execute_total{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "DB Queries"
    },
    {
     "expr": "sum(irate(cacheops_cache_hit_total{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "sum(irate(cacheops_cache_miss_total{job=~\"$job\", namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Cache Miss"
    }
   ]
  }
 ]
}